language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y build-essential libgphoto2-2-dev
  - pkg-config --list-all
  - pkg-config --libs libgphoto2
  - pkg-config --modversion libgphoto2
