[package]
name = "gphoto2-sys"
version = "0.1.0"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]

build = "build.rs"
links = "gphoto2"

[dependencies]
libc = "0.1.10"

[build-dependencies]
pkg-config = "0.3.2"
